export const quotes = [
  {
    id: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p",
    quote: "Be yourself; everyone else is already taken.",
    author: "Oscar Wilde",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "2b3c4d5e-6f7g-8h9i-0j1k-2l3m4n5o6p7q",
    quote: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "3c4d5e6f-7g8h-9i0j-1k2l-3m4n5o6p7q8r",
    quote: "In the middle of difficulty lies opportunity.",
    author: "Albert Einstein",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "4d5e6f7g-8h9i-0j1k-2l3m-4n5o6p7q8r9s",
    quote: "What you do today can improve all your tomorrows.",
    author: "Ralph Marston",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "5e6f7g8h-9i0j-1k2l-3m4n-5o6p7q8r9s0t",
    quote: "It always seems impossible until it’s done.",
    author: "Nelson Mandela",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "6f7g8h9i-0j1k-2l3m-4n5o-6p7q8r9s0t1u",
    quote: "If you can dream it, you can do it.",
    author: "Walt Disney",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "7g8h9i0j-1k2l-3m4n-5o6p-7q8r9s0t1u2v",
    quote: "Stay hungry. Stay foolish.",
    author: "Steve Jobs",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "8h9i0j1k-2l3m-4n5o-6p7q-8r9s0t1u2v3w",
    quote: "Whatever you are, be a good one.",
    author: "Abraham Lincoln",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "9i0j1k2l-3m4n-5o6p-7q8r-9s0t1u2v3w4x",
    quote: "Strive not to be a success, but rather to be of value.",
    author: "Albert Einstein",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "0j1k2l3m-4n5o-6p7q-8r9s-0t1u2v3w4x5y",
    quote: "Simplicity is the ultimate sophistication.",
    author: "Leonardo da Vinci",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "1k2l3m4n-5o6p-7q8r-9s0t-1u2v3w4x5y6z",
    quote: "Life is short. Live it.",
    author: "Unknown",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "2l3m4n5o-6p7q-8r9s-0t1u-2v3w4x5y6z7a",
    quote: "Act as if what you do makes a difference. It does.",
    author: "William James",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "3m4n5o6p-7q8r-9s0t-1u2v-3w4x5y6z7a8b",
    quote: "Turn your wounds into wisdom.",
    author: "Oprah Winfrey",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "4n5o6p7q-8r9s-0t1u-2v3w-4x5y6z7a8b9c",
    quote: "You miss 100% of the shots you don’t take.",
    author: "Wayne Gretzky",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "5o6p7q8r-9s0t-1u2v-3w4x-5y6z7a8b9c0d",
    quote: "Dream big and dare to fail.",
    author: "Norman Vaughan",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "6p7q8r9s-0t1u-2v3w-4x5y-6z7a8b9c0d1e",
    quote: "Don’t wait. The time will never be just right.",
    author: "Napoleon Hill",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "7q8r9s0t-1u2v-3w4x-5y6z-7a8b9c0d1e2f",
    quote: "Well done is better than well said.",
    author: "Benjamin Franklin",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "8r9s0t1u-2v3w-4x5y-6z7a-8b9c0d1e2f3g",
    quote: "Be the change that you wish to see in the world.",
    author: "Often attributed to Gandhi",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "9s0t1u2v-3w4x-5y6z-7a8b-9c0d1e2f3g4h",
    quote: "Happiness is not by chance, but by choice.",
    author: "Jim Rohn",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "0t1u2v3w-4x5y-6z7a-8b9c-0d1e2f3g4h5i",
    quote: "Action is the foundational key to all success.",
    author: "Pablo Picasso",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "1u2v3w4x-5y6z-7a8b-9c0d-1e2f3g4h5i6j",
    quote: "Do something today that your future self will thank you for.",
    author: "Sean Patrick Flanery",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "2v3w4x5y-6z7a-8b9c-0d1e-2f3g4h5i6j7k",
    quote:
      "It’s not the years in your life that count. It’s the life in your years.",
    author: "Abraham Lincoln",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "3w4x5y6z-7a8b-9c0d-1e2f-3g4h5i6j7k8l",
    quote: "Either you run the day or the day runs you.",
    author: "Jim Rohn",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "4x5y6z7a-8b9c-0d1e-2f3g-4h5i6j7k8l9m",
    quote: "Believe you can and you’re halfway there.",
    author: "Theodore Roosevelt",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "5y6z7a8b-9c0d-1e2f-3g4h-5i6j7k8l9m0n",
    quote: "Failure is success if we learn from it.",
    author: "Malcolm Forbes",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "6z7a8b9c-0d1e-2f3g-4h5i-6j7k8l9m0n1o",
    quote: "Life is 10% what happens to us and 90% how we react to it.",
    author: "Charles R. Swindoll",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "7a8b9c0d-1e2f-3g4h-5i6j-7k8l9m0n1o2p",
    quote: "Start where you are. Use what you have. Do what you can.",
    author: "Arthur Ashe",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "8b9c0d1e-2f3g-4h5i-6j7k-8l9m0n1o2p3q",
    quote: "What we think, we become.",
    author: "Buddha",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "9c0d1e2f-3g4h-5i6j-7k8l-9m0n1o2p3q4r",
    quote:
      "Keep going. Everything you need will come to you at the perfect time.",
    author: "Unknown",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "0d1e2f3g-4h5i-6j7k-8l9m-0n1o2p3q4r5s",
    quote: "Success is not final; failure is not fatal.",
    author: "Winston Churchill",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "1e2f3g4h-5i6j-7k8l-9m0n-1o2p3q4r5s6t",
    quote: "A person who never made a mistake never tried anything new.",
    author: "Albert Einstein",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "2f3g4h5i-6j7k-8l9m-0n1o-2p3q4r5s6t7u",
    quote: "Don’t let yesterday take up too much of today.",
    author: "Will Rogers",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "3g4h5i6j-7k8l-9m0n-1o2p-3q4r5s6t7u8v",
    quote: "Everything you’ve ever wanted is on the other side of fear.",
    author: "George Addair",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "4h5i6j7k-8l9m-0n1o-2p3q-4r5s6t7u8v9w",
    quote: "I have not failed. I’ve just found 10,000 ways that won’t work.",
    author: "Thomas Edison",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "5i6j7k8l-9m0n-1o2p-3q4r-5s6t7u8v9w0x",
    quote: "If you want to lift yourself up, lift up someone else.",
    author: "Booker T. Washington",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "6j7k8l9m-0n1o-2p3q-4r5s-6t7u8v9w0x1y",
    quote: "Don’t be pushed around by the fears in your mind.",
    author: "Roy T. Bennett",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "7k8l9m0n-1o2p-3q4r-5s6t-7u8v9w0x1y2z",
    quote: "Small deeds done are better than great deeds planned.",
    author: "Peter Marshall",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "8l9m0n1o-2p3q-4r5s-6t7u-8v9w0x1y2z3a",
    quote: "We may encounter many defeats but we must not be defeated.",
    author: "Maya Angelou",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "9m0n1o2p-3q4r-5s6t-7u8v-9w0x1y2z3a4b",
    quote: "Be kind whenever possible. It is always possible.",
    author: "Dalai Lama",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "0n1o2p3q-4r5s-6t7u-8v9w-0x1y2z3a4b5c",
    quote: "To succeed in life, you need two things: ignorance and confidence.",
    author: "Mark Twain",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "1o2p3q4r-5s6t-7u8v-9w0x-1y2z3a4b5c6d",
    quote:
      "The only limit to our realization of tomorrow will be our doubts of today.",
    author: "Franklin D. Roosevelt",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "2p3q4r5s-6t7u-8v9w-0x1y-2z3a4b5c6d7e",
    quote:
      "You can, you should, and if you’re brave enough to start, you will.",
    author: "Stephen King",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "3q4r5s6t-7u8v-9w0x-1y2z-3a4b5c6d7e8f",
    quote: "If at first you don’t succeed, try, try again.",
    author: "Thomas H. Palmer",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "4r5s6t7u-8v9w-0x1y-2z3a-4b5c6d7e8f9g",
    quote: "It’s kind of fun to do the impossible.",
    author: "Walt Disney",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "5s6t7u8v-9w0x-1y2z-3a4b-5c6d7e8f9g0h",
    quote: "If opportunity doesn’t knock, build a door.",
    author: "Milton Berle",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "6t7u8v9w-0x1y-2z3a-4b5c-6d7e8f9g0h1i",
    quote: "Fall seven times, stand up eight.",
    author: "Japanese Proverb",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "7u8v9w0x-1y2z-3a4b-5c6d-7e8f9g0h1i2j",
    quote: "A journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "8v9w0x1y-2z3a-4b5c-6d7e-8f9g0h1i2j3k",
    quote: "Never regret anything that made you smile.",
    author: "Mark Twain",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "9w0x1y2z-3a4b-5c6d-7e8f-9g0h1i2j3k4l",
    quote: "Die with memories, not dreams.",
    author: "Unknown",
    likeCount: 0,
    dislikeCount: 0,
  },
  {
    id: "0x1y2z3a-4b5c-6d7e-8f9g-0h1i2j3k4l5m",
    quote: "I can and I will. Watch me.",
    author: "Carrie Green (often credited)",
    likeCount: 0,
    dislikeCount: 0,
  },
];
